### ISSUE TITLE
Add support for ThenInclude(...) on Enumerables

### ISSUE THREAD

**Issue by rvanoord** [bcc-code/bcc-linq#59]
Currently .ThenInclude(...) only works after a non-enumerable object. Often it needs to be applied to an enumerable.

For example.

```
client.Persons.GetQueryable().Include(p => p.Affiliations).ThenInclude(a => a.Org)
````

Note that Affiliations in the example above is a List of affiliations.

**Comment by leo-schick** [comment]
Can you help me understand what the issue is? I implemented `Include`/``ThenInclude` similar to how Entity Framework Core implements it. This example should work according to the unit test [IncludeThenIncludeTest()](https://github.com/bcc-code/bcc-linq/blob/main/tests/BccCode.Linq.Tests/LinqTests.cs#L2116-L2135). What is it what needs to be fixed here?

p.s. `Include` and `ThenInclude` is implemented for `IQueryable<T>`, not for `IEnumerable` or `IEnumerable<T>` instances.

**Comment by rvanoord** [comment]
Entity framework actually has two implementations of ThenInclude. One where the previous object is a reference and the other one where it is an IEnumerable<>. It's the IEnumerable implementation that's missing

**Comment by leo-schick** [comment]
@rvanoord I can only find one implementation in Entity Framework Core for IQueryable [here](https://github.com/dotnet/efcore/blob/76ff7a3acca089fa087bd98db6fcac8f2f057794/src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs#L2382).

**Comment by rvanoord** [comment]
See https://github.com/dotnet/efcore/blob/76ff7a3acca089fa087bd98db6fcac8f2f057794/src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs#L2413

and

https://github.com/dotnet/efcore/blob/76ff7a3acca089fa087bd98db6fcac8f2f057794/src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs#L2447

@leo-schick
